apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: i5ruth5af-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/i5ruth5af-java-quarkus-gitops